version: '3'

vars:
  DOCKER_DIR: docker
  SERVICE: ros2-humble-utility
  PROJECT: rosenv

tasks:
  check-env:
    dir: "{{.DOCKER_DIR}}"
    dotenv: ['.env']
    preconditions:
      - sh: '[ "$RUNTIME_ENV" = "nvidia" ] || [ "$RUNTIME_ENV" = "wsl" ] || [ "$RUNTIME_ENV" = "nogpu" ]'
        msg: "RUNTIME_ENV is invalid."

  update-env:
    dir: "{{.DOCKER_DIR}}"
    dotenv: ['.env']
    silent: true
    cmds:
      - "sed -i -e 's/UID=.*$/UID='$(id -u)'/g' .env"
      - "sed -i -e 's/GID=.*$/GID='$(id -g)'/g' .env"
      - "sed -i -e 's/GID_AUDIO=.*$/GID_AUDIO='$(getent group audio | cut -d: -f3)'/g' .env"
      - "sed -i -e 's/GID_DIALOUT=.*$/GID_DIALOUT='$(getent group dialout | cut -d: -f3)'/g' .env"
      - "sed -i -e 's/GID_VIDEO=.*$/GID_VIDEO='$(getent group video | cut -d: -f3)'/g' .env"
      - "sed -i -e 's/GID_I2C=.*$/GID_I2C='$(getent group i2c | cut -d: -f3)'/g' .env"

  up-host:
    desc: docker compose up host
    dir: "{{.DOCKER_DIR}}"
    dotenv: ['.env']
    env:
      NETWORK_MODE: host
    silent: true
    cmds:
      - "sed -i -e 's/NETWORK_MODE=.*$/NETWORK_MODE='${NETWORK_MODE}'/g' .env"
      - task: update-env
      - task: check-env
      - task: compose-up

  up-bridge:
    desc: docker compose up bridge
    dir: "{{.DOCKER_DIR}}"
    dotenv: ['.env']
    env:
      NETWORK_MODE: bridge
    silent: true
    cmds:
      - "sed -i -e 's/NETWORK_MODE=.*$/NETWORK_MODE='${NETWORK_MODE}'/g' .env"
      - task: update-env
      - task: check-env
      - task: compose-up

  exec:
    desc: docker compose exec
    dir: "{{.DOCKER_DIR}}"
    dotenv: ['.env']
    silent: true
    cmds:
      - task: check-env
      - task: compose-exec

  stop:
    desc: docker compose stop
    dir: "{{.DOCKER_DIR}}"
    dotenv: ['.env']
    silent: true
    cmds:
      - task: check-env
      - task: compose-stop

  build:
    desc: docker compose build
    dir: "{{.DOCKER_DIR}}"
    dotenv: ['.env']
    silent: true
    cmds:
      - task: update-env
      - task: check-env
      - task: compose-build

  compose-up:
    dir: "{{.DOCKER_DIR}}"
    dotenv: ['.env']
    silent: true
    cmds:
      - "PWD=$(pwd) docker compose -f ${NETWORK_MODE}.${RUNTIME_ENV}.compose.yml -p {{.PROJECT}} up -d"

  compose-exec:
    dir: "{{.DOCKER_DIR}}"
    dotenv: ['.env']
    silent: true
    cmds:
      - "PWD=$(pwd) docker compose -f ${NETWORK_MODE}.${RUNTIME_ENV}.compose.yml  -p {{.PROJECT}} exec {{.SERVICE}} /bin/bash"

  compose-stop:
    dir: "{{.DOCKER_DIR}}"
    dotenv: ['.env']
    silent: true
    cmds:
      - "PWD=$(pwd) docker compose -f ${NETWORK_MODE}.${RUNTIME_ENV}.compose.yml  -p {{.PROJECT}} stop"

  compose-build:
    dir: "{{.DOCKER_DIR}}"
    dotenv: ['.env']
    silent: true
    cmds:
      - "PWD=$(pwd) docker compose -f ${NETWORK_MODE}.${RUNTIME_ENV}.compose.yml build"
