
services:

    ros2-humble-utility:
        build:
            context: .
            dockerfile: Dockerfile
            args:
            - UID=${UID}
            - GID=${GID}
            - USER_NAME=${USER_NAME}
            - BUILD_TARGET=${BUILD_TARGET}
            - BUILD_WITH_CUDA=${BUILD_WITH_CUDA}
            - GID_AUDIO=${GID_AUDIO}
            - GID_DIALOUT=${GID_DIALOUT}
            - GID_VIDEO=${GID_VIDEO}
            - GID_I2C=${GID_I2C}
        image: rosenv:ros2-humble-utility
        container_name: ros2-humble-utility
        sysctls:
            net.ipv4.ipfrag_time: 3
            net.ipv4.ipfrag_high_thresh: 134217728
        #stdin_open: true
        tty: true
        devices:
        - /dev/snd:/dev/snd
        - /dev/dri:/dev/dri
        env_file:
        - .env
        environment:
        - DISPLAY=${DISPLAY}
        volumes:
        - /dev:/dev
        - /tmp/.X11-unix:/tmp/.X11-unix
        - ${PWD}/home:/home/${USER_NAME}/mnt
        - ${PWD}/tmp:/home/${USER_NAME}/mnt/tmp
        - ${PWD}/setup:/setup
