version: '3'
services:

    ros2-humble-official-01:
        build:
            context: .
            dockerfile: Dockerfile
            args:
            - UID=${UID}
            - GID=${GID}
            - USER=${USER}
            - BUILD_TARGET=${BUILD_TARGET}
            - BUILD_WITH_CUDA=${BUILD_WITH_CUDA}
        image: rosenv:ros2-humble-official-01
        container_name: ros2-humble-official-01
        user: ${UID}:${GID}
        #stdin_open: true
        tty: true
        environment:
        - DISPLAY=${DISPLAY}
        - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
        volumes:
        - /dev:/dev
        - /tmp/.X11-unix:/tmp/.X11-unix
        - ${PWD}/home:/home/${USER}/mnt
        - ${PWD}/tmp:/home/${USER}/mnt/tmp
        - ${PWD}/setup:/setup
